bitoid/bksi

web/themes/custom/bksi/bksi.libraries.yml, web/themes/custom/bksi/js/dropdown.js, web/themes/custom/bksi/js/impressium.js, web/themes/custom/bksi/js/karriere-dropdown.js, web/themes/custom/bksi/js/lazy-loading.js, web/themes/custom/bksi/js/main.js, web/themes/custom/bksi/js/slider.js
#104 Importing from https://github.com/Chkhikvadzeg/BKSI JS files and importing in bks theme folder in bksi.libraries.yml
=> 104 import js files from desing

web/modules/custom/bksi_default_content/content/node/062999f0-d93e-4975-91a0-62c4a0874c33.yml
=> #41 - create and export team page

web/modules/custom/bksi_default_content/content/node/7e90be5c-fed5-43fc-9387-0b4c5883e081.yml
=> #96 Create and export 'Services' page

web/themes/custom/bksi/src/tailwind.pcss, web/themes/custom/bksi/tailwind.config.js
=> #56 update tailwind.pcss & tailwind.config.js

config/sync/block_content.type.contacts.yml, config/sync/core.entity_form_display.block_content.contacts.default.yml, config/sync/core.entity_view_display.block_content.contacts.default.yml, config/sync/field.field.block_content.contacts.field_email.yml, config/sync/field.field.block_content.contacts.field_phone_number.yml, config/sync/field.field.block_content.contacts.field_slogan.yml, config/sync/field.field.block_content.contacts.field_title.yml, config/sync/field.storage.block_content.field_email.yml, config/sync/field.storage.block_content.field_phone_number.yml, web/modules/custom/bksi_default_content/content/block_content/a70afd5f-2f36-43b5-ab08-d1922db818aa.yml, web/modules/custom/bksi_default_content/content/node/7e90be5c-fed5-43fc-9387-0b4c5883e081.yml, web/themes/custom/bksi/bksi.theme, web/themes/custom/bksi/images/Bilder/Arrows&Navigation/arrow-kontaktmodul.svg, web/themes/custom/bksi/templates/block/block--bundle--contacts.html.twig
=> 9 implement contact custom block type for contact page

config/sync/block_content.type.motto.yml, config/sync/core.entity_form_display.block_content.motto.default.yml, config/sync/core.entity_view_display.block_content.motto.default.yml, config/sync/field.field.block_content.motto.field_author.yml, config/sync/field.field.block_content.motto.field_motto.yml, config/sync/field.storage.block_content.field_author.yml, config/sync/field.storage.block_content.field_motto.yml, web/modules/custom/bksi_default_content/content/block_content/36d48753-aee5-4c34-804e-b3a03e2aa5c1.yml, web/modules/custom/bksi_default_content/content/node/7e90be5c-fed5-43fc-9387-0b4c5883e081.yml, web/themes/custom/bksi/templates/block/block--bundle--motto.html.twig
=> 10 implement motto custom block type for services page

config/sync/block_content.type.text_section_with_cta.yml, config/sync/core.entity_form_display.block_content.text_section_with_cta.default.yml, config/sync/core.entity_view_display.block_content.text_section_with_cta.default.yml, config/sync/field.field.block_content.text_section_with_cta.field_link_cta.yml, config/sync/field.field.block_content.text_section_with_cta.field_paragraph.yml, config/sync/field.field.block_content.text_section_with_cta.field_slogan.yml, config/sync/field.field.block_content.text_section_with_cta.field_title.yml, config/sync/field.storage.block_content.field_link_cta.yml, config/sync/field.storage.block_content.field_paragraph.yml, web/modules/custom/bksi_default_content/content/block_content/0e463375-7ccf-4408-82d8-d686e4889261.yml, web/modules/custom/bksi_default_content/content/node/e4e063bb-9490-46ff-82ae-06f09a6ebae5.yml, web/themes/custom/bksi/templates/block/block--bundle--text-section-with-cta.html.twig
=> 4 implement text section with cta

config/sync/core.extension.yml, config/sync/image.style.original.yml, web/modules/custom/projects/projects.info.yml, web/modules/custom/projects/projects.routing.yml, web/modules/custom/projects/src/Controller/ProjectsController.php
=> #16 implement projects json endpoint

composer.json, composer.lock, config/sync/core.extension.yml, web/modules/custom/bksi_contact_form/bksi_contact_form.info.yml, web/modules/custom/bksi_contact_form/src/Form/ContactForm.php, web/modules/custom/bksi_contact_form/src/Plugin/Block/ContactFormBlock.php, web/modules/custom/bksi_default_content/content/node/18df5fce-c219-4784-a70d-630a7c7877c9.yml, web/themes/custom/bksi/templates/block/block--bksi-contact-form.html.twig, web/themes/custom/bksi/templates/form/contact/elements/form-element--bksi-contact-form--email.html.twig, web/themes/custom/bksi/templates/form/contact/elements/form-element--bksi-contact-form--files-file.html.twig, web/themes/custom/bksi/templates/form/contact/elements/form-element--bksi-contact-form--message.html.twig, web/themes/custom/bksi/templates/form/contact/elements/form-element--bksi-contact-form--name.html.twig, web/themes/custom/bksi/templates/form/contact/elements/form-element--bksi-contact-form--phone.html.twig, web/themes/custom/bksi/templates/form/contact/elements/form-element--bksi-contact-form--policy-checkbox.html.twig, web/themes/custom/bksi/templates/form/contact/elements/form-element--bksi-contact-form--surname.html.twig, web/themes/custom/bksi/templates/form/contact/form--bksi-contact-form.html.twig, web/themes/custom/bksi/templates/form/contact/inputs/input--checkbox--bksi-contact-form--policy-checkbox.html.twig, web/themes/custom/bksi/templates/form/contact/inputs/input--email--bksi-contact-form.html.twig, web/themes/custom/bksi/templates/form/contact/inputs/input--file--bksi-contact-form--files-file.html.twig, web/themes/custom/bksi/templates/form/contact/inputs/input--submit--bksi-contact-form--op.html.twig, web/themes/custom/bksi/templates/form/contact/inputs/input--tel--bksi-contact-form.html.twig, web/themes/custom/bksi/templates/form/contact/inputs/input--textfield--bksi-contact-form.html.twig, web/themes/custom/bksi/templates/form/contact/inputs/textarea--bksi-contact-form.html.twig
Isuue #49 
**Before testing**
1. Install Font-awesome (see: https://github.com/bitoid/bksi/pull/25#issuecomment-1224842716)
2. Install Formdazzle module `composer require 'drupal/formdazzle:^2.1'`
3. Copy code from https://github.com/Chkhikvadzeg/BKSI/blob/master/style/style.css to src/tailwind.pcss
4. Copy config from https://github.com/Chkhikvadzeg/BKSI/blob/master/tailwind.config.js to tailwind.config.js, **don't copy `content variable`** 
5. Run `npm install`
6. Run `npm install -D tailwindcss-hyphens`
7. Run `npm run dev`
=> 49 create web form block type for ask detail page

config/sync/core.extension.yml, web/modules/custom/bksi_default_content/content/file/1f047d5e-0e89-412a-924f-8c8f3178db24.yml, web/modules/custom/bksi_default_content/content/file/7c879390-f089-4615-8f71-6bd42e4e356f.yml, web/modules/custom/bksi_default_content/content/file/f2427df9-02dc-49a6-84f4-17bfc2820a8d.yml, web/modules/custom/bksi_default_content/content/node/7e90be5c-fed5-43fc-9387-0b4c5883e081.yml, web/modules/custom/bksi_default_content/content/node/e4e063bb-9490-46ff-82ae-06f09a6ebae5.yml, web/modules/custom/bksi_services/bksi_services.info.yml, web/modules/custom/bksi_services/bksi_services.module, web/modules/custom/bksi_services/src/Plugin/Block/BksiServices.php, web/modules/custom/bksi_services/templates/bksi-services.html.twig
=> #160 create bksi services module

web/modules/custom/bksi_career/src/Plugin/Block/BksiCareer.php
=> 155 implement custom block plugin for career page

config/sync/field.storage.block_content.field_text_block_description.yml
=> #180 Delete multiple option in text block description field

web/modules/custom/bksi_default_content/content/block_content/8fd82dda-9d58-4e3a-9e3b-97bc333e3c27.yml, web/modules/custom/bksi_default_content/content/block_content/b4eef42c-33f8-425b-8faf-d21045ca4187.yml, web/modules/custom/bksi_default_content/content/file/1f047d5e-0e89-412a-924f-8c8f3178db24.yml, web/modules/custom/bksi_default_content/content/file/7c879390-f089-4615-8f71-6bd42e4e356f.yml, web/modules/custom/bksi_default_content/content/file/f2427df9-02dc-49a6-84f4-17bfc2820a8d.yml, web/modules/custom/bksi_default_content/content/node/7e90be5c-fed5-43fc-9387-0b4c5883e081.yml, web/modules/custom/bksi_default_content/content/node/e4e063bb-9490-46ff-82ae-06f09a6ebae5.yml
=> 181 text section with cta home page

web/modules/custom/bksi_default_content/content/block_content/d51c06bb-6b2b-4f03-93ac-06e9cc231c1e.yml, web/modules/custom/bksi_default_content/content/node/25f62a78-df82-4238-8199-616f4df80e14.yml, web/modules/custom/bksi_default_content/content/node/2f81d860-65bb-48da-b940-2e976868e492.yml, web/modules/custom/bksi_default_content/content/node/61fcc4aa-383b-41dc-bc79-456f2ea8043c.yml, web/modules/custom/bksi_default_content/content/node/87abcd56-135d-4fe5-aecc-59e6e4a1edc4.yml, web/modules/custom/bksi_default_content/content/node/8dc3fff3-c33e-431c-967e-62aef2a77afd.yml, web/modules/custom/bksi_default_content/content/node/b00a2d5f-2840-4fcd-8745-5d772acd0a16.yml, web/modules/custom/bksi_default_content/content/node/c12b41eb-9816-494c-add1-ebc5825198ca.yml, web/modules/custom/bksi_default_content/content/node/cc451855-a329-4845-964f-546aab937a98.yml, web/modules/custom/bksi_default_content/content/node/e05becc5-9b46-4010-9fa5-847d1ba8b059.yml, web/modules/custom/bksi_default_content/content/node/e4e063bb-9490-46ff-82ae-06f09a6ebae5.yml, web/modules/custom/bksi_default_content/content/node/ffbee4c3-b1f1-4c5f-94e5-6d5ce6c35670.yml, web/modules/custom/bksi_news/bksi_news.info.yml, web/modules/custom/bksi_news/src/Service/BksiNewsService.php, web/modules/custom/bksi_news/templates/bksi-news.html.twig
=> 192 replace body field with summary in bksi news

web/themes/custom/bksi/js/main.js
=> #194 add background on headers

web/modules/custom/projects/js/script.js, web/modules/custom/projects/templates/projects.html.twig
=> #19 add check mark image on list items

web/themes/custom/bksi/js/randomProjects.js
=> #193 - Modifie random projects logicon projects detailed page

config/sync/field.field.node.project.field_project_sector.yml, config/sync/field.field.node.project.field_project_service.yml, config/sync/field.field.node.project.field_project_type.yml, config/sync/field.storage.node.field_project_sector.yml, config/sync/field.storage.node.field_project_service.yml, config/sync/field.storage.node.field_project_type.yml
=> #202 - Modifie projects building sector and service field settings

web/themes/custom/bksi/templates/block/block--mainmenu.html.twig
=> 3 implement site search

web/modules/custom/projects/js/script.js, web/modules/custom/projects/templates/projects.html.twig
=> #204 - modifie js script file

config/sync/core.extension.yml, config/sync/system.site.yml, web/modules/custom/bksi_contact_email_field/bksi_contact_email_field.info.yml, web/modules/custom/bksi_contact_email_field/bksi_contact_email_field.module
=> #170 Add contact email field in site details

config/sync/node.type.article.yml, config/sync/node.type.customer.yml, config/sync/node.type.job.yml, config/sync/node.type.project.yml, config/sync/node.type.services.yml
=> #211 remove available menus from content type

composer.json, composer.lock, config/sync/core.entity_view_mode.block.token.yml, config/sync/core.entity_view_mode.block_content.token.yml, config/sync/core.entity_view_mode.comment.token.yml, config/sync/core.entity_view_mode.contact_message.token.yml, config/sync/core.entity_view_mode.file.token.yml, config/sync/core.entity_view_mode.menu_link_content.token.yml, config/sync/core.entity_view_mode.node.token.yml, config/sync/core.entity_view_mode.paragraph.token.yml, config/sync/core.entity_view_mode.path_alias.token.yml, config/sync/core.entity_view_mode.shortcut.token.yml, config/sync/core.entity_view_mode.taxonomy_term.token.yml, config/sync/core.entity_view_mode.tour.token.yml, config/sync/core.entity_view_mode.user.token.yml, config/sync/core.extension.yml, config/sync/pathauto.pattern.alias_pattern_for_any_content_type.yml, config/sync/pathauto.settings.yml, config/sync/system.action.pathauto_update_alias_node.yml, config/sync/system.action.pathauto_update_alias_user.yml, web/modules/custom/bksi_career/templates/bksi-career.html.twig, web/modules/custom/bksi_news/templates/bksi-news.html.twig, web/modules/custom/bksi_services/templates/bksi-services.html.twig, web/modules/custom/projects/js/script.js, web/modules/custom/projects/src/Controller/ProjectsController.php
=> #212 Install and configure Pathauto module

composer.json, composer.lock, config/sync/core.entity_form_display.user.user.default.yml, config/sync/core.extension.yml, config/sync/shield.settings.yml, web/modules/custom/bksi_news/src/Plugin/Block/BksiNews.php
=> 218 http authentication

web/themes/custom/bksi/js/main.js, web/themes/custom/bksi/templates/layout/page.html.twig
=> #215 fix admin toolbar

config/sync/image.style.large.yml, config/sync/image.style.large_webp.yml, config/sync/image.style.original_webp.yml, web/modules/custom/bksi_news/src/Service/BksiNewsService.php, web/modules/custom/bksi_news/templates/bksi-news.html.twig
=> #214 Convert images to webp

config/sync/system.site.yml, web/modules/custom/bksi_default_content/content/menu_link_content/442384f9-c9a5-442f-9845-bfa6f934a022.yml, web/themes/custom/bksi/src/tailwind.pcss, web/themes/custom/bksi/templates/node/node--job.html.twig
=> 224 rework feedback frontend desktop

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/image.style.large.yml, config/sync/image.style.large_webp.yml, web/modules/custom/bksi_career/src/Plugin/Block/BksiCareer.php, web/modules/custom/bksi_career/templates/bksi-career.html.twig, web/modules/custom/bksi_customers/src/Plugin/Block/BksiCustomers.php, web/modules/custom/bksi_customers/templates/bksi-customers.html.twig, web/modules/custom/bksi_news/templates/bksi-news.html.twig, web/modules/custom/projects/js/script.js, web/modules/custom/projects/src/Controller/ProjectsController.php, web/themes/custom/bksi/bksi.theme, web/themes/custom/bksi/js/randomProjects.js, web/themes/custom/bksi/templates/block/block--bundle--application.html.twig, web/themes/custom/bksi/templates/block/block--bundle--contact-block-type.html.twig, web/themes/custom/bksi/templates/block/block--bundle--customers.html.twig, web/themes/custom/bksi/templates/block/block--bundle--directors.html.twig, web/themes/custom/bksi/templates/block/block--bundle--footer-logo.html.twig, web/themes/custom/bksi/templates/block/block--bundle--impressions.html.twig, web/themes/custom/bksi/templates/block/block--bundle--job.html.twig, web/themes/custom/bksi/templates/block/block--inline-block--hero-block-type.html.twig, web/themes/custom/bksi/templates/block/block--inline-block--services.html.twig, web/themes/custom/bksi/templates/field/image--company-detail.html.twig, web/themes/custom/bksi/templates/field/image--team-gallery.html.twig, web/themes/custom/bksi/templates/node/node--project.html.twig
=> 214 convert images in webp
